version: "3.9"
services:
  mongodb:
    image: mongo:7.0.9
    # restart: always
    container_name: hospitaldb
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
  flask-service:
    build:
      context: ./flask_app
    image: flask_app
    # restart: always
    container_name: flask_app
    depends_on:
      - mongodb
    ports:
      - 5000:5000
    environment:
      - "SERVER_HOST=0.0.0.0"
      - "MONGO_HOST=mongodb"
      - "MONGO_DATABASE=HospitalDB"